version: '3'
services: 
    web: # You can call the app whatever you want
        stdin_open: true
        build:
            context: . # All files come from current dir. YOu can specify that here
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app # maps pwd(.) to app which is inside the container
    tests: # service for test (Not the best idea, but one way to do it)
        stdin_open: true
        build:
            context: . # All files come from current dir. YOu can specify that here
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app # maps pwd(.) to app which is inside the container
        command: ["npm", "run", "test"] # overrides the docker startup